#import Exception

class MyCustomError(Exception):
    pass